--CREATE DATABASE RACEDAYDB;

--CREATE TABLE USERS (
--    userID INT IDENTITY(1,1) PRIMARY KEY,
--    email VARCHAR(255) UNIQUE NOT NULL,
--    passwordHash VARCHAR(255) NOT NULL,
--    fullName VARCHAR(255) NOT NULL,
--    phone VARCHAR(50),
--    created_at DATETIME DEFAULT GETDATE(),
--    updated_at DATETIME DEFAULT GETDATE()
--);

CREATE TABLE ORGANISERS (
    organiserID INT IDENTITY(1,1) PRIMARY KEY,
    userID INT NOT NULL UNIQUE REFERENCES USERS(userID) ON DELETE CASCADE,
    companyName VARCHAR(255),
    created_at DATETIME DEFAULT GETDATE(),
    updated_at DATETIME DEFAULT GETDATE()
);